services:
  postgres:
    container_name: wolf-wallet-postgres-dev
  wolf-wallet-app:
    build: ./app
    image: wolfgangkp/wolf-wallet:dev
    container_name: wolf-wallet-app-dev
    env_file:
      - .env
    volumes:
      - ./app:/app # Bind mount (should match WORKDIR in Dockerfile)
    ports:
      - "5001:5000"
    command: sh -c "npm i && npm run dev"
